// <auto-generated />
namespace needHelp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_user_request : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_user_request));
        
        string IMigrationMetadata.Id
        {
            get { return "201605020419340_change_user_request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
