// <auto-generated />
namespace needHelp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_requests_for_orgs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_requests_for_orgs));
        
        string IMigrationMetadata.Id
        {
            get { return "201605070212014_fix_requests_for_orgs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
